# Generated by Django 3.2.12 on 2022-10-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221021_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='task',
            name='green',
        ),
        migrations.RemoveField(
            model_name='task',
            name='red',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#aa00ff', max_length=9),
        ),
    ]
